name: Run Robot Framework Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          pabot --testlevelsplit --processes 8 ./online_bookstore
        continue-on-error: true

      - name: Get current working directory
        id: get-pwd
        run: echo "cwd=$(pwd)" >> $GITHUB_OUTPUT

      - name: copy reports to reports/ folder
        run: |
          cp ${{ steps.get-pwd.outputs.cwd }}/report.html ${{ steps.get-pwd.outputs.cwd }}/reports/report.html  
          cp ${{ steps.get-pwd.outputs.cwd }}/report.html ${{ steps.get-pwd.outputs.cwd }}/reports/output.xml  
          cp ${{ steps.get-pwd.outputs.cwd }}/report.html ${{ steps.get-pwd.outputs.cwd }}/reports/log.html  

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: |
            ${{ steps.get-pwd.outputs.cwd }}/reports/report.html
            ${{ steps.get-pwd.outputs.cwd }}/reports/output.xml
            ${{ steps.get-pwd.outputs.cwd }}/reports/log.html
          retention-days: 7

      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: robot-reports

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
