name: Run Robot Framework Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:     # Manual trigger
    inputs:
      environment:
        type: choice
        description: 'environment to run the tests against'
        options:
          - dev
          - prod
        required: true
        default: dev

jobs:
  robot-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: |
          pabot --testlevelsplit --processes 8  --outputdir  ./reports --variable env:{{ github.event.inputs.environment }} ./online_bookstore
        continue-on-error: true

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: |
            ./reports/report.html
            ./reports/output.xml
            ./reports/log.html
          retention-days: 7

      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: robot-reports

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.5
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
